version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-java-spring
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Download Java CLIs
          command: |
            wget https://stormrunner-load.saas.hpe.com/external/storm-cli/storm_runner_java_cli.zip
           
      - run:  
          name: Run StormRunner Test
          command: |
            unzip storm_runner_java_cli.zip
            java -jar cli.jar runWithResult testId=922 connect=Anushree.Nagar@mheducation.com:P@ssw0rd@Oct2018@https://stormrunner-load.saas.hpe.com tenant=949194025:109 sendEmail=True
            cd /tmp
            fileName=$(ls -t1 *.csv | head -n 1)
            echo "Filename: $fileName"
            
      - run: 
          name: Connect to ArtiFactory
          command: |
            curl -fL https://getcli.jfrog.io | sh
            ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD --interactive=true
            jfrog rt s Perf-Dashboard/Collectors/SR-resultFile-CircleCI
