version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
	      name: Start StormRunner
		    command: curl -O https://stormrunner-load.saas.hpe.com/v2/load-tests?TENANTID=949194025&projectId=109
