version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-java-spring
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Download Java CLI
          command: |
            curl -O https://admhelp.microfocus.com/srl/en/3.2/Content/Storm/t_JenkinsIntegration.htm#java_cli/storm_runner_java_cli
      - run:    
          command: |
            javac -version
            
      
