version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-java-spring
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Download Java CLI
          command: |
            wget https://stormrunner-load.saas.hpe.com/external/storm-cli/storm_runner_java_cli.zip
           
      - run:    
          command: |
            unzip storm_runner_java_cli.zip
            ls -l
            java -jar cli.jar getResult runId=922 connect=Anushree.Nagar@mheducation.com:P@ssw0rd@Oct2018@https://stormrunner-load.saas.hpe.com tenant=949194025:109 sendEmail=True
