version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-java-spring
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Download Java CLI
          command: |
            wget https://stormrunner-load.saas.hpe.com/external/storm-cli/storm_runner_java_cli.zip
           
      - run:    
          command: |
            unzip storm_runner_java_cli.zip
            java -jar cli.jar runWithResult testId=922 connect=Anushree.Nagar@mheducation.com:P@ssw0rd@Oct2018@https://stormrunner-load.saas.hpe.com tenant=949194025:109 sendEmail=True
            curl -X GET --header 'Accept: application/json' 'https://stormrunner-load.saas.hpe.com/v1/projects/109/load-tests/922/runs?TENANTID=949194025'
            
